version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kibou
      POSTGRES_PASSWORD: kiboupass
      POSTGRES_DB: kibou
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    # Wait for db, run migrations & seeds, then start the server
    command: sh -c "until pg_isready -h db -p 5432; do sleep 1; done && npx knex migrate:latest --knexfile knexfile.ts && npx knex seed:run --knexfile knexfile.ts && npm run dev"
    volumes:
      - ./backend:/app
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://kibou:kiboupass@db:5432/kibou
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4000
    depends_on:
      - backend

volumes:
  db_data: 