import { Knex } from "knex";
import bcrypt from 'bcryptjs';

export async function seed(knex: Knex): Promise<void> {
    // Delete in order: applications, tenders, goods_and_services, user_company_map, companies, users
    await knex("applications").del();
    await knex("tenders").del();
    await knex("goods_and_services").del();
    await knex("user_company_map").del();
    await knex("companies").del();
    await knex("users").del();

    // USERS
    const users = [
        { id: 1, email: 'user1@example.com', password: 'password' },
        { id: 2, email: 'user2@example.com', password: 'password' },
        { id: 3, email: 'user3@example.com', password: 'password' },
        { id: 4, email: 'user4@example.com', password: 'password' },
        { id: 5, email: 'user5@example.com', password: 'password' },
        { id: 6, email: 'user6@example.com', password: 'password' },
        { id: 7, email: 'user7@example.com', password: 'password' },
        { id: 8, email: 'user8@example.com', password: 'password' },
        { id: 9, email: 'user9@example.com', password: 'password' },
        { id: 10, email: 'user10@example.com', password: 'password' },
    ];
    const hashedUsers = await Promise.all(users.map(async (u) => ({
        id: u.id,
        email: u.email,
        password_hash: await bcrypt.hash(u.password, 10),
    })));
    await knex("users").insert(hashedUsers);

    // COMPANIES
    await knex("companies").insert([
        { id: 1, name: 'Acme Corp', industry: 'Manufacturing', description: 'Leading manufacturer of widgets' },
        { id: 2, name: 'Beta LLC', industry: 'Consulting', description: 'Business consulting services' },
        { id: 3, name: 'Company 3', industry: 'Industry', description: 'Company 3 description' },
        { id: 4, name: 'Company 4', industry: 'Industry', description: 'Company 4 description' },
        { id: 5, name: 'Company 5', industry: 'Industry', description: 'Company 5 description' },
        { id: 6, name: 'Company 6', industry: 'Industry', description: 'Company 6 description' },
        { id: 7, name: 'Company 7', industry: 'Industry', description: 'Company 7 description' },
        { id: 8, name: 'Company 8', industry: 'Industry', description: 'Company 8 description' },
        { id: 9, name: 'Company 9', industry: 'Industry', description: 'Company 9 description' },
        { id: 10, name: 'Company 10', industry: 'Industry', description: 'Company 10 description' },
        { id: 11, name: 'Company 11', industry: 'Industry', description: 'Company 11 description' },
        { id: 12, name: 'Company 12', industry: 'Industry', description: 'Company 12 description' },
        { id: 13, name: 'Company 13', industry: 'Industry', description: 'Company 13 description' },
        { id: 14, name: 'Company 14', industry: 'Industry', description: 'Company 14 description' },
        { id: 15, name: 'Company 15', industry: 'Industry', description: 'Company 15 description' },
        { id: 16, name: 'Company 16', industry: 'Industry', description: 'Company 16 description' },
        { id: 17, name: 'Company 17', industry: 'Industry', description: 'Company 17 description' },
        { id: 18, name: 'Company 18', industry: 'Industry', description: 'Company 18 description' },
        { id: 19, name: 'Company 19', industry: 'Industry', description: 'Company 19 description' },
        { id: 20, name: 'Company 20', industry: 'Industry', description: 'Company 20 description' },
        { id: 21, name: 'Company 21', industry: 'Industry', description: 'Company 21 description' },
        { id: 22, name: 'Company 22', industry: 'Industry', description: 'Company 22 description' },
        { id: 23, name: 'Company 23', industry: 'Industry', description: 'Company 23 description' },
        { id: 24, name: 'Company 24', industry: 'Industry', description: 'Company 24 description' },
        { id: 25, name: 'Company 25', industry: 'Industry', description: 'Company 25 description' },
        { id: 26, name: 'Company 26', industry: 'Industry', description: 'Company 26 description' },
        { id: 27, name: 'Company 27', industry: 'Industry', description: 'Company 27 description' },
        { id: 28, name: 'Company 28', industry: 'Industry', description: 'Company 28 description' },
        { id: 29, name: 'Company 29', industry: 'Industry', description: 'Company 29 description' },
        { id: 30, name: 'Company 30', industry: 'Industry', description: 'Company 30 description' },
        { id: 31, name: 'Company 31', industry: 'Industry', description: 'Company 31 description' },
        { id: 32, name: 'Company 32', industry: 'Industry', description: 'Company 32 description' },
        { id: 33, name: 'Company 33', industry: 'Industry', description: 'Company 33 description' },
        { id: 34, name: 'Company 34', industry: 'Industry', description: 'Company 34 description' },
        { id: 35, name: 'Company 35', industry: 'Industry', description: 'Company 35 description' },
        { id: 36, name: 'Company 36', industry: 'Industry', description: 'Company 36 description' },
        { id: 37, name: 'Company 37', industry: 'Industry', description: 'Company 37 description' },
        { id: 38, name: 'Company 38', industry: 'Industry', description: 'Company 38 description' },
        { id: 39, name: 'Company 39', industry: 'Industry', description: 'Company 39 description' },
        { id: 40, name: 'Company 40', industry: 'Industry', description: 'Company 40 description' },
        { id: 41, name: 'Company 41', industry: 'Industry', description: 'Company 41 description' },
        { id: 42, name: 'Company 42', industry: 'Industry', description: 'Company 42 description' },
        { id: 43, name: 'Company 43', industry: 'Industry', description: 'Company 43 description' },
        { id: 44, name: 'Company 44', industry: 'Industry', description: 'Company 44 description' },
        { id: 45, name: 'Company 45', industry: 'Industry', description: 'Company 45 description' },
        { id: 46, name: 'Company 46', industry: 'Industry', description: 'Company 46 description' },
        { id: 47, name: 'Company 47', industry: 'Industry', description: 'Company 47 description' },
        { id: 48, name: 'Company 48', industry: 'Industry', description: 'Company 48 description' },
        { id: 49, name: 'Company 49', industry: 'Industry', description: 'Company 49 description' },
        { id: 50, name: 'Company 50', industry: 'Industry', description: 'Company 50 description' },
        { id: 51, name: 'Sigma Tech', industry: 'Technology', description: 'Tech solutions provider' },
        { id: 52, name: 'Delta Foods', industry: 'Food', description: 'Food distributor' },
        { id: 53, name: 'Omega Health', industry: 'Healthcare', description: 'Healthcare services' },
        { id: 54, name: 'Alpha Retail', industry: 'Retail', description: 'Retail chain' },
        { id: 55, name: 'Beta Energy', industry: 'Energy', description: 'Energy provider' },
        { id: 56, name: 'Gamma Logistics', industry: 'Logistics', description: 'Logistics company' },
        { id: 57, name: 'Theta Media', industry: 'Media', description: 'Media agency' },
        { id: 58, name: 'Zeta Finance', industry: 'Finance', description: 'Financial services' },
        { id: 59, name: 'Eta Design', industry: 'Design', description: 'Design studio' },
        { id: 60, name: 'Kappa Consulting', industry: 'Consulting', description: 'Consulting firm' },
    ]);

    // USER_COMPANY_MAP
    await knex("user_company_map").insert([
        { user_id: 1, company_id: 1 },
        { user_id: 2, company_id: 2 },
        { user_id: 3, company_id: 51 },
        { user_id: 4, company_id: 52 },
        { user_id: 5, company_id: 53 },
        { user_id: 6, company_id: 54 },
        { user_id: 7, company_id: 55 },
        { user_id: 8, company_id: 56 },
        { user_id: 9, company_id: 57 },
        { user_id: 10, company_id: 58 },
        { user_id: 3, company_id: 59 },
        { user_id: 4, company_id: 60 },
    ]);

    // GOODS_AND_SERVICES
    await knex("goods_and_services").insert([
        { id: 1, company_id: 1, name: 'Widgets' },
        { id: 2, company_id: 1, name: 'Gadgets' },
        { id: 3, company_id: 2, name: 'Cloud Hosting' },
        { id: 4, company_id: 2, name: 'AI Consulting' },
        { id: 5, company_id: 3, name: 'Parts' },
        { id: 6, company_id: 3, name: 'Assembly' },
        { id: 7, company_id: 4, name: 'Security' },
        { id: 8, company_id: 4, name: 'Networking' },
        { id: 9, company_id: 5, name: 'Logistics' },
        { id: 10, company_id: 5, name: 'Warehousing' },
        { id: 11, company_id: 6, name: 'Strategy' },
        { id: 12, company_id: 6, name: 'Operations' },
        { id: 13, company_id: 7, name: 'Retail' },
        { id: 14, company_id: 7, name: 'E-commerce' },
        { id: 15, company_id: 8, name: 'Solar' },
        { id: 16, company_id: 8, name: 'Wind' },
        { id: 17, company_id: 9, name: 'Groceries' },
        { id: 18, company_id: 9, name: 'Delivery' },
        { id: 19, company_id: 10, name: 'Healthcare' },
        { id: 20, company_id: 10, name: 'Pharmacy' },
        { id: 21, company_id: 11, name: 'Media' },
        { id: 22, company_id: 11, name: 'Advertising' },
        { id: 23, company_id: 12, name: 'Banking' },
        { id: 24, company_id: 12, name: 'Investments' },
        { id: 25, company_id: 13, name: 'Transport' },
        { id: 26, company_id: 13, name: 'Logistics' },
        { id: 27, company_id: 14, name: 'Construction' },
        { id: 28, company_id: 14, name: 'Engineering' },
        { id: 29, company_id: 15, name: 'Interior Design' },
        { id: 30, company_id: 15, name: 'Architecture' },
        { id: 31, company_id: 16, name: 'Cybersecurity' },
        { id: 32, company_id: 16, name: 'Surveillance' },
        { id: 33, company_id: 17, name: 'Sports Equipment' },
        { id: 34, company_id: 17, name: 'Training' },
        { id: 35, company_id: 18, name: 'Travel' },
        { id: 36, company_id: 18, name: 'Tourism' },
        { id: 37, company_id: 19, name: 'Event Planning' },
        { id: 38, company_id: 19, name: 'Catering' },
        { id: 39, company_id: 20, name: 'Online Courses' },
        { id: 40, company_id: 20, name: 'Tutoring' },
        { id: 41, company_id: 21, name: 'Biotech' },
        { id: 42, company_id: 21, name: 'Research' },
        { id: 43, company_id: 22, name: 'Fashion' },
        { id: 44, company_id: 22, name: 'Accessories' },
        { id: 45, company_id: 23, name: 'Art' },
        { id: 46, company_id: 23, name: 'Exhibitions' },
        { id: 47, company_id: 24, name: 'Publishing' },
        { id: 48, company_id: 24, name: 'Editing' },
        { id: 49, company_id: 25, name: 'Consulting' },
        { id: 50, company_id: 25, name: 'Business Analysis' },
        { id: 51, company_id: 26, name: 'Industry Service 1' },
        { id: 52, company_id: 26, name: 'Industry Service 2' },
        { id: 53, company_id: 27, name: 'Industry Service 1' },
        { id: 54, company_id: 27, name: 'Industry Service 2' },
        { id: 55, company_id: 28, name: 'Industry Service 1' },
        { id: 56, company_id: 28, name: 'Industry Service 2' },
        { id: 57, company_id: 29, name: 'Industry Service 1' },
        { id: 58, company_id: 29, name: 'Industry Service 2' },
        { id: 59, company_id: 30, name: 'Industry Service 1' },
        { id: 60, company_id: 30, name: 'Industry Service 2' },
        { id: 61, company_id: 31, name: 'Industry Service 1' },
        { id: 62, company_id: 31, name: 'Industry Service 2' },
        { id: 63, company_id: 32, name: 'Industry Service 1' },
        { id: 64, company_id: 32, name: 'Industry Service 2' },
        { id: 65, company_id: 33, name: 'Industry Service 1' },
        { id: 66, company_id: 33, name: 'Industry Service 2' },
        { id: 67, company_id: 34, name: 'Industry Service 1' },
        { id: 68, company_id: 34, name: 'Industry Service 2' },
        { id: 69, company_id: 35, name: 'Industry Service 1' },
        { id: 70, company_id: 35, name: 'Industry Service 2' },
        { id: 71, company_id: 36, name: 'Industry Service 1' },
        { id: 72, company_id: 36, name: 'Industry Service 2' },
        { id: 73, company_id: 37, name: 'Industry Service 1' },
        { id: 74, company_id: 37, name: 'Industry Service 2' },
        { id: 75, company_id: 38, name: 'Industry Service 1' },
        { id: 76, company_id: 38, name: 'Industry Service 2' },
        { id: 77, company_id: 39, name: 'Industry Service 1' },
        { id: 78, company_id: 39, name: 'Industry Service 2' },
        { id: 79, company_id: 40, name: 'Industry Service 1' },
        { id: 80, company_id: 40, name: 'Industry Service 2' },
        { id: 81, company_id: 41, name: 'Industry Service 1' },
        { id: 82, company_id: 41, name: 'Industry Service 2' },
        { id: 83, company_id: 42, name: 'Industry Service 1' },
        { id: 84, company_id: 42, name: 'Industry Service 2' },
        { id: 85, company_id: 43, name: 'Industry Service 1' },
        { id: 86, company_id: 43, name: 'Industry Service 2' },
        { id: 87, company_id: 44, name: 'Industry Service 1' },
        { id: 88, company_id: 44, name: 'Industry Service 2' },
        { id: 89, company_id: 45, name: 'Industry Service 1' },
        { id: 90, company_id: 45, name: 'Industry Service 2' },
        { id: 91, company_id: 46, name: 'Industry Service 1' },
        { id: 92, company_id: 46, name: 'Industry Service 2' },
        { id: 93, company_id: 47, name: 'Industry Service 1' },
        { id: 94, company_id: 47, name: 'Industry Service 2' },
        { id: 95, company_id: 48, name: 'Industry Service 1' },
        { id: 96, company_id: 48, name: 'Industry Service 2' },
        { id: 97, company_id: 49, name: 'Industry Service 1' },
        { id: 98, company_id: 49, name: 'Industry Service 2' },
        { id: 99, company_id: 50, name: 'Industry Service 1' },
        { id: 100, company_id: 50, name: 'Industry Service 2' },
        { id: 101, company_id: 51, name: 'Cloud Services' },
        { id: 102, company_id: 51, name: 'IT Support' },
        { id: 103, company_id: 52, name: 'Catering' },
        { id: 104, company_id: 52, name: 'Wholesale' },
        { id: 105, company_id: 53, name: 'Medical Devices' },
        { id: 106, company_id: 53, name: 'Pharmacy' },
        { id: 107, company_id: 54, name: 'E-commerce' },
        { id: 108, company_id: 54, name: 'In-store Sales' },
        { id: 109, company_id: 55, name: 'Solar Power' },
        { id: 110, company_id: 55, name: 'Wind Power' },
        { id: 111, company_id: 56, name: 'Freight' },
        { id: 112, company_id: 56, name: 'Warehousing' },
        { id: 113, company_id: 57, name: 'Advertising' },
        { id: 114, company_id: 57, name: 'Content Creation' },
        { id: 115, company_id: 58, name: 'Loans' },
        { id: 116, company_id: 58, name: 'Investments' },
        { id: 117, company_id: 59, name: 'Branding' },
        { id: 118, company_id: 59, name: 'UX/UI Design' },
        { id: 119, company_id: 60, name: 'Strategy' },
        { id: 120, company_id: 60, name: 'Operations' },
    ]);

    // TENDERS
    await knex("tenders").insert([
        { id: 1, company_id: 1, title: 'Widget Supply', description: 'Need widget suppliers.', deadline: '2025-12-31', budget: '50000' },
        { id: 2, company_id: 2, title: 'AI Platform', description: 'Seeking AI platform proposals.', deadline: '2025-11-30', budget: '120000' },
        { id: 3, company_id: 3, title: 'Parts Procurement', description: 'Looking for parts suppliers.', deadline: '2025-10-15', budget: '30000' },
        { id: 4, company_id: 4, title: 'Security Upgrade', description: 'Upgrade security systems.', deadline: '2025-09-01', budget: '40000' },
        { id: 5, company_id: 5, title: 'Logistics Contract', description: 'Logistics for new plant.', deadline: '2025-08-20', budget: '35000' },
        { id: 6, company_id: 6, title: 'Strategy Consulting', description: 'Business strategy advice.', deadline: '2025-07-15', budget: '60000' },
        { id: 7, company_id: 7, title: 'Retail Expansion', description: 'Expand retail presence.', deadline: '2025-06-10', budget: '45000' },
        { id: 8, company_id: 8, title: 'Renewable Energy', description: 'Solar and wind project.', deadline: '2025-05-05', budget: '80000' },
        { id: 9, company_id: 9, title: 'Food Delivery', description: 'Expand food delivery.', deadline: '2025-04-01', budget: '25000' },
        { id: 10, company_id: 10, title: 'Healthcare App', description: 'Develop healthcare app.', deadline: '2025-03-15', budget: '70000' },
        { id: 11, company_id: 11, title: 'Media Campaign', description: 'Launch media campaign.', deadline: '2025-02-10', budget: '55000' },
        { id: 12, company_id: 12, title: 'Investment Platform', description: 'Build investment platform.', deadline: '2025-01-05', budget: '90000' },
        { id: 13, company_id: 13, title: 'Transport Fleet', description: 'Expand transport fleet.', deadline: '2024-12-01', budget: '65000' },
        { id: 14, company_id: 14, title: 'Construction Project', description: 'New office building.', deadline: '2024-11-15', budget: '110000' },
        { id: 15, company_id: 15, title: 'Design Contract', description: 'Office design project.', deadline: '2024-10-10', budget: '30000' },
        { id: 16, company_id: 16, title: 'Cybersecurity Audit', description: 'Audit security systems.', deadline: '2024-09-05', budget: '50000' },
        { id: 17, company_id: 17, title: 'Sports Event', description: 'Organize sports event.', deadline: '2024-08-01', budget: '20000' },
        { id: 18, company_id: 18, title: 'Travel Booking', description: 'Corporate travel booking.', deadline: '2024-07-15', budget: '40000' },
        { id: 19, company_id: 19, title: 'Event Management', description: 'Manage annual event.', deadline: '2024-06-10', budget: '35000' },
        { id: 20, company_id: 20, title: 'Online Course', description: 'Develop online course.', deadline: '2024-05-05', budget: '15000' },
        { id: 21, company_id: 21, title: 'Biotech Research', description: 'Research project.', deadline: '2024-04-01', budget: '120000' },
        { id: 22, company_id: 22, title: 'Fashion Show', description: 'Organize fashion show.', deadline: '2024-03-15', budget: '25000' },
        { id: 23, company_id: 23, title: 'Art Exhibition', description: 'Host art exhibition.', deadline: '2024-02-10', budget: '18000' },
        { id: 24, company_id: 24, title: 'Book Publishing', description: 'Publish new book.', deadline: '2024-01-05', budget: '22000' },
        { id: 25, company_id: 25, title: 'Business Analysis', description: 'Business analysis project.', deadline: '2023-12-01', budget: '40000' },
        { id: 26, company_id: 26, title: 'Industry Tender 1', description: 'Tender for company 26.', deadline: '2023-11-15', budget: '30000' },
        { id: 27, company_id: 27, title: 'Industry Tender 2', description: 'Tender for company 27.', deadline: '2023-10-10', budget: '35000' },
        { id: 28, company_id: 28, title: 'Industry Tender 3', description: 'Tender for company 28.', deadline: '2023-09-05', budget: '32000' },
        { id: 29, company_id: 29, title: 'Industry Tender 4', description: 'Tender for company 29.', deadline: '2023-08-01', budget: '31000' },
        { id: 30, company_id: 30, title: 'Industry Tender 5', description: 'Tender for company 30.', deadline: '2023-07-15', budget: '33000' },
        { id: 31, company_id: 31, title: 'Industry Tender 6', description: 'Tender for company 31.', deadline: '2023-06-10', budget: '34000' },
        { id: 32, company_id: 32, title: 'Industry Tender 7', description: 'Tender for company 32.', deadline: '2023-05-05', budget: '36000' },
        { id: 33, company_id: 33, title: 'Industry Tender 8', description: 'Tender for company 33.', deadline: '2023-04-01', budget: '37000' },
        { id: 34, company_id: 34, title: 'Industry Tender 9', description: 'Tender for company 34.', deadline: '2023-03-15', budget: '38000' },
        { id: 35, company_id: 35, title: 'Industry Tender 10', description: 'Tender for company 35.', deadline: '2023-02-10', budget: '39000' },
        { id: 36, company_id: 36, title: 'Industry Tender 11', description: 'Tender for company 36.', deadline: '2023-01-05', budget: '40000' },
        { id: 37, company_id: 37, title: 'Industry Tender 12', description: 'Tender for company 37.', deadline: '2022-12-01', budget: '41000' },
        { id: 38, company_id: 38, title: 'Industry Tender 13', description: 'Tender for company 38.', deadline: '2022-11-15', budget: '42000' },
        { id: 39, company_id: 39, title: 'Industry Tender 14', description: 'Tender for company 39.', deadline: '2022-10-10', budget: '43000' },
        { id: 40, company_id: 40, title: 'Industry Tender 15', description: 'Tender for company 40.', deadline: '2022-09-05', budget: '44000' },
        { id: 41, company_id: 41, title: 'Industry Tender 16', description: 'Tender for company 41.', deadline: '2022-08-01', budget: '45000' },
        { id: 42, company_id: 42, title: 'Industry Tender 17', description: 'Tender for company 42.', deadline: '2022-07-15', budget: '46000' },
        { id: 43, company_id: 43, title: 'Industry Tender 18', description: 'Tender for company 43.', deadline: '2022-06-10', budget: '47000' },
        { id: 44, company_id: 44, title: 'Industry Tender 19', description: 'Tender for company 44.', deadline: '2022-05-05', budget: '48000' },
        { id: 45, company_id: 45, title: 'Industry Tender 20', description: 'Tender for company 45.', deadline: '2022-04-01', budget: '49000' },
        { id: 46, company_id: 46, title: 'Industry Tender 21', description: 'Tender for company 46.', deadline: '2022-03-15', budget: '50000' },
        { id: 47, company_id: 47, title: 'Industry Tender 22', description: 'Tender for company 47.', deadline: '2022-02-10', budget: '51000' },
        { id: 48, company_id: 48, title: 'Industry Tender 23', description: 'Tender for company 48.', deadline: '2022-01-05', budget: '52000' },
        { id: 49, company_id: 49, title: 'Industry Tender 24', description: 'Tender for company 49.', deadline: '2021-12-01', budget: '53000' },
        { id: 50, company_id: 50, title: 'Industry Tender 25', description: 'Tender for company 50.', deadline: '2021-11-15', budget: '54000' },
        { id: 51, company_id: 51, title: 'Tech Upgrade', description: 'Upgrade IT infrastructure.', deadline: '2026-01-01', budget: '100000' },
        { id: 52, company_id: 52, title: 'Food Supply', description: 'Supply food for events.', deadline: '2026-02-01', budget: '20000' },
        { id: 53, company_id: 53, title: 'Healthcare App', description: 'Develop a healthcare app.', deadline: '2026-03-01', budget: '50000' },
        { id: 54, company_id: 54, title: 'Retail Expansion', description: 'Open new retail stores.', deadline: '2026-04-01', budget: '75000' },
        { id: 55, company_id: 55, title: 'Green Energy', description: 'Install solar panels.', deadline: '2026-05-01', budget: '120000' },
        { id: 56, company_id: 56, title: 'Logistics Contract', description: 'Manage logistics for new plant.', deadline: '2026-06-01', budget: '40000' },
        { id: 57, company_id: 57, title: 'Media Campaign', description: 'Launch new media campaign.', deadline: '2026-07-01', budget: '30000' },
        { id: 58, company_id: 58, title: 'Financial Audit', description: 'Audit financial statements.', deadline: '2026-08-01', budget: '25000' },
        { id: 59, company_id: 59, title: 'Rebranding', description: 'Rebrand company image.', deadline: '2026-09-01', budget: '35000' },
        { id: 60, company_id: 60, title: 'Business Consulting', description: 'Consulting for business growth.', deadline: '2026-10-01', budget: '60000' },
        { id: 61, company_id: 51, title: 'Cloud Migration', description: 'Migrate to cloud.', deadline: '2026-11-01', budget: '80000' },
        { id: 62, company_id: 52, title: 'Event Catering', description: 'Catering for annual event.', deadline: '2026-12-01', budget: '15000' },
        { id: 63, company_id: 53, title: 'Medical Equipment', description: 'Procure new medical equipment.', deadline: '2027-01-01', budget: '90000' },
        { id: 64, company_id: 54, title: 'Online Store', description: 'Develop online store.', deadline: '2027-02-01', budget: '40000' },
        { id: 65, company_id: 55, title: 'Wind Farm', description: 'Build wind farm.', deadline: '2027-03-01', budget: '130000' },
        { id: 66, company_id: 56, title: 'Warehouse Expansion', description: 'Expand warehouse capacity.', deadline: '2027-04-01', budget: '50000' },
        { id: 67, company_id: 57, title: 'Content Series', description: 'Produce content series.', deadline: '2027-05-01', budget: '20000' },
        { id: 68, company_id: 58, title: 'Investment Platform', description: 'Develop investment platform.', deadline: '2027-06-01', budget: '70000' },
        { id: 69, company_id: 59, title: 'UX Redesign', description: 'Redesign user experience.', deadline: '2027-07-01', budget: '30000' },
        { id: 70, company_id: 60, title: 'Market Research', description: 'Conduct market research.', deadline: '2027-08-01', budget: '25000' },
    ]);

    // APPLICATIONS
    await knex("applications").insert([
        { id: 1, tender_id: 1, company_id: 2, proposal: 'Globex can supply widgets.' },
        { id: 2, tender_id: 2, company_id: 1, proposal: 'Acme can build your AI platform.' },
        { id: 3, tender_id: 3, company_id: 2, proposal: 'Globex can supply parts.' },
        { id: 4, tender_id: 4, company_id: 1, proposal: 'Acme can upgrade security.' },
        { id: 5, tender_id: 5, company_id: 2, proposal: 'Globex can handle logistics.' },
        { id: 6, tender_id: 6, company_id: 1, proposal: 'Acme can consult on strategy.' },
        { id: 7, tender_id: 7, company_id: 2, proposal: 'Globex can expand retail.' },
        { id: 8, tender_id: 8, company_id: 1, proposal: 'Acme can deliver renewable energy.' },
        { id: 9, tender_id: 9, company_id: 2, proposal: 'Globex can expand food delivery.' },
        { id: 10, tender_id: 10, company_id: 1, proposal: 'Acme can develop healthcare app.' },
        { id: 11, tender_id: 11, company_id: 2, proposal: 'Globex can launch media campaign.' },
        { id: 12, tender_id: 12, company_id: 1, proposal: 'Acme can build investment platform.' },
        { id: 13, tender_id: 13, company_id: 2, proposal: 'Globex can expand transport.' },
        { id: 14, tender_id: 14, company_id: 1, proposal: 'Acme can build office.' },
        { id: 15, tender_id: 15, company_id: 2, proposal: 'Globex can design office.' },
        { id: 16, tender_id: 16, company_id: 1, proposal: 'Acme can audit security.' },
        { id: 17, tender_id: 17, company_id: 2, proposal: 'Globex can organize sports event.' },
        { id: 18, tender_id: 18, company_id: 1, proposal: 'Acme can book travel.' },
        { id: 19, tender_id: 19, company_id: 2, proposal: 'Globex can manage event.' },
        { id: 20, tender_id: 20, company_id: 1, proposal: 'Acme can develop course.' },
        { id: 21, tender_id: 21, company_id: 2, proposal: 'Globex can do biotech research.' },
        { id: 22, tender_id: 22, company_id: 1, proposal: 'Acme can organize fashion show.' },
        { id: 23, tender_id: 23, company_id: 2, proposal: 'Globex can host art exhibition.' },
        { id: 24, tender_id: 24, company_id: 1, proposal: 'Acme can publish book.' },
        { id: 25, tender_id: 25, company_id: 2, proposal: 'Globex can analyze business.' },
        { id: 26, tender_id: 26, company_id: 1, proposal: 'Acme can do industry tender 1.' },
        { id: 27, tender_id: 27, company_id: 2, proposal: 'Globex can do industry tender 2.' },
        { id: 28, tender_id: 28, company_id: 1, proposal: 'Acme can do industry tender 3.' },
        { id: 29, tender_id: 29, company_id: 2, proposal: 'Globex can do industry tender 4.' },
        { id: 30, tender_id: 30, company_id: 1, proposal: 'Acme can do industry tender 5.' },
        { id: 31, tender_id: 31, company_id: 2, proposal: 'Globex can do industry tender 6.' },
        { id: 32, tender_id: 32, company_id: 1, proposal: 'Acme can do industry tender 7.' },
        { id: 33, tender_id: 33, company_id: 2, proposal: 'Globex can do industry tender 8.' },
        { id: 34, tender_id: 34, company_id: 1, proposal: 'Acme can do industry tender 9.' },
        { id: 35, tender_id: 35, company_id: 2, proposal: 'Globex can do industry tender 10.' },
        { id: 36, tender_id: 36, company_id: 1, proposal: 'Acme can do industry tender 11.' },
        { id: 37, tender_id: 37, company_id: 2, proposal: 'Globex can do industry tender 12.' },
        { id: 38, tender_id: 38, company_id: 1, proposal: 'Acme can do industry tender 13.' },
        { id: 39, tender_id: 39, company_id: 2, proposal: 'Globex can do industry tender 14.' },
        { id: 40, tender_id: 40, company_id: 1, proposal: 'Acme can do industry tender 15.' },
        { id: 41, tender_id: 41, company_id: 2, proposal: 'Globex can do industry tender 16.' },
        { id: 42, tender_id: 42, company_id: 1, proposal: 'Acme can do industry tender 17.' },
        { id: 43, tender_id: 43, company_id: 2, proposal: 'Globex can do industry tender 18.' },
        { id: 44, tender_id: 44, company_id: 1, proposal: 'Acme can do industry tender 19.' },
        { id: 45, tender_id: 45, company_id: 2, proposal: 'Globex can do industry tender 20.' },
        { id: 46, tender_id: 46, company_id: 1, proposal: 'Acme can do industry tender 21.' },
        { id: 47, tender_id: 47, company_id: 2, proposal: 'Globex can do industry tender 22.' },
        { id: 48, tender_id: 48, company_id: 1, proposal: 'Acme can do industry tender 23.' },
        { id: 49, tender_id: 49, company_id: 2, proposal: 'Globex can do industry tender 24.' },
        { id: 50, tender_id: 50, company_id: 1, proposal: 'Acme can do industry tender 25.' },
        { id: 51, tender_id: 51, company_id: 52, proposal: 'Delta Foods can provide catering.' },
        { id: 52, tender_id: 52, company_id: 53, proposal: 'Omega Health can supply medical staff.' },
        { id: 53, tender_id: 53, company_id: 54, proposal: 'Alpha Retail can market the app.' },
        { id: 54, tender_id: 54, company_id: 55, proposal: 'Beta Energy can power new stores.' },
        { id: 55, tender_id: 55, company_id: 56, proposal: 'Gamma Logistics can deliver panels.' },
        { id: 56, tender_id: 56, company_id: 57, proposal: 'Theta Media can promote logistics.' },
        { id: 57, tender_id: 57, company_id: 58, proposal: 'Zeta Finance can fund the campaign.' },
        { id: 58, tender_id: 58, company_id: 59, proposal: 'Eta Design can design audit reports.' },
        { id: 59, tender_id: 59, company_id: 60, proposal: 'Kappa Consulting can manage rebranding.' },
        { id: 60, tender_id: 60, company_id: 51, proposal: 'Sigma Tech can consult for growth.' },
        { id: 61, tender_id: 61, company_id: 52, proposal: 'Delta Foods can cater migration event.' },
        { id: 62, tender_id: 62, company_id: 53, proposal: 'Omega Health can provide healthy meals.' },
        { id: 63, tender_id: 63, company_id: 54, proposal: 'Alpha Retail can sell equipment.' },
        { id: 64, tender_id: 64, company_id: 55, proposal: 'Beta Energy can power online store.' },
        { id: 65, tender_id: 65, company_id: 56, proposal: 'Gamma Logistics can deliver turbines.' },
        { id: 66, tender_id: 66, company_id: 57, proposal: 'Theta Media can promote expansion.' },
        { id: 67, tender_id: 67, company_id: 58, proposal: 'Zeta Finance can invest in content.' },
        { id: 68, tender_id: 68, company_id: 59, proposal: 'Eta Design can design platform.' },
        { id: 69, tender_id: 69, company_id: 60, proposal: 'Kappa Consulting can research UX.' },
        { id: 70, tender_id: 70, company_id: 51, proposal: 'Sigma Tech can analyze market.' },
    ]);

    await knex.raw(`SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));`);
    await knex.raw(`SELECT setval('companies_id_seq', (SELECT MAX(id) FROM companies));`);
    await knex.raw(`SELECT setval('goods_and_services_id_seq', (SELECT MAX(id) FROM goods_and_services));`);
    await knex.raw(`SELECT setval('tenders_id_seq', (SELECT MAX(id) FROM tenders));`);
    await knex.raw(`SELECT setval('applications_id_seq', (SELECT MAX(id) FROM applications));`);
}
